using System.Text.Json;
using System.Text.Json.Serialization;
using VSCopilotSwitch.Core.Providers;
using VSCopilotSwitch.Services;
using VSCopilotSwitch.VsCodeConfig.Models;

namespace VSCopilotSwitch;

[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ErrorMessageResponse))]
[JsonSerializable(typeof(Vs2026ByomInfoResponse))]
[JsonSerializable(typeof(ApplyVsCodeOllamaConfigRequest))]
[JsonSerializable(typeof(VsCodeUserDirectoryRequest))]
[JsonSerializable(typeof(RemoveVsCodeOllamaConfigRequest))]
[JsonSerializable(typeof(ListVsCodeConfigBackupsRequest))]
[JsonSerializable(typeof(RestoreVsCodeConfigBackupRequest))]
[JsonSerializable(typeof(VsCodeConfigApplyResult))]
[JsonSerializable(typeof(VsCodeOllamaConfigStatus))]
[JsonSerializable(typeof(VsCodeConfigFileChange))]
[JsonSerializable(typeof(VsCodeConfigFieldChange))]
[JsonSerializable(typeof(VsCodeConfigBackup))]
[JsonSerializable(typeof(VsCodeConfigRestoreResult))]
[JsonSerializable(typeof(SaveProviderConfigRequest))]
[JsonSerializable(typeof(TestProviderConnectionRequest))]
[JsonSerializable(typeof(ReorderProvidersRequest))]
[JsonSerializable(typeof(ProviderConnectionTestResult))]
[JsonSerializable(typeof(ProviderConnectionTestStep))]
[JsonSerializable(typeof(ProviderConfigExportDocument))]
[JsonSerializable(typeof(ProviderConfigExportItem))]
[JsonSerializable(typeof(RequestAnalyticsSnapshot))]
[JsonSerializable(typeof(RequestAnalyticsSummary))]
[JsonSerializable(typeof(ListenerStatus))]
[JsonSerializable(typeof(RequestLogEntry))]
[JsonSerializable(typeof(CopilotCompatibilityProbeResult))]
[JsonSerializable(typeof(CopilotCompatibilityProbeStep))]
[JsonSerializable(typeof(DashboardProviderConfigView))]
[JsonSerializable(typeof(DashboardTagsResponse))]
[JsonSerializable(typeof(DashboardModelInfo))]
[JsonSerializable(typeof(DashboardModelDetails))]
[JsonSerializable(typeof(DashboardVsCodeUserDirectory))]
[JsonSerializable(typeof(IReadOnlyList<DashboardProviderConfigView>))]
[JsonSerializable(typeof(IReadOnlyList<DashboardModelInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DashboardVsCodeUserDirectory>))]
[JsonSerializable(typeof(IReadOnlyList<VsCodeConfigBackup>))]
[JsonSerializable(typeof(IReadOnlyList<VsCodeConfigFileChange>))]
[JsonSerializable(typeof(IReadOnlyList<VsCodeConfigFieldChange>))]
[JsonSerializable(typeof(IReadOnlyList<ProviderConnectionTestStep>))]
[JsonSerializable(typeof(IReadOnlyList<ProviderConfigExportItem>))]
[JsonSerializable(typeof(IReadOnlyList<RequestLogEntry>))]
[JsonSerializable(typeof(IReadOnlyList<CopilotCompatibilityProbeStep>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
internal sealed partial class MewUiJsonContext : JsonSerializerContext;
