using System.Text.Json;
using System.Text.Json.Serialization;
using VSCopilotSwitch.Core.Ollama;
using VSCopilotSwitch.Core.Providers;
using VSCopilotSwitch.Services;
using VSCopilotSwitch.VsCodeConfig.Models;

[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ErrorMessageResponse))]
[JsonSerializable(typeof(HostInfoResponse))]
[JsonSerializable(typeof(OpenExternalUrlRequest))]
[JsonSerializable(typeof(OpenExternalUrlResult))]
[JsonSerializable(typeof(PortStatusResponse))]
[JsonSerializable(typeof(OllamaVersionResponse))]
[JsonSerializable(typeof(ApplyVsCodeOllamaConfigRequest))]
[JsonSerializable(typeof(VsCodeUserDirectoryRequest))]
[JsonSerializable(typeof(RemoveVsCodeOllamaConfigRequest))]
[JsonSerializable(typeof(ListVsCodeConfigBackupsRequest))]
[JsonSerializable(typeof(RestoreVsCodeConfigBackupRequest))]
[JsonSerializable(typeof(OllamaTagsResponse))]
[JsonSerializable(typeof(OllamaModelInfo))]
[JsonSerializable(typeof(OllamaModelInfo[]))]
[JsonSerializable(typeof(OllamaModelDetails))]
[JsonSerializable(typeof(OllamaChatRequest))]
[JsonSerializable(typeof(OllamaShowRequest))]
[JsonSerializable(typeof(OllamaShowResponse))]
[JsonSerializable(typeof(OllamaChatMessage))]
[JsonSerializable(typeof(OllamaChatResponse))]
[JsonSerializable(typeof(OllamaErrorResponse))]
[JsonSerializable(typeof(ProviderModel))]
[JsonSerializable(typeof(ProviderModel[]))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(ChatRequest))]
[JsonSerializable(typeof(ChatResponse))]
[JsonSerializable(typeof(ChatStreamChunk))]
[JsonSerializable(typeof(ProviderConnectionTestStep))]
[JsonSerializable(typeof(ProviderConnectionTestResult))]
[JsonSerializable(typeof(ProviderConfigView))]
[JsonSerializable(typeof(ProviderConfigView[]))]
[JsonSerializable(typeof(ProviderConfigExportDocument))]
[JsonSerializable(typeof(ProviderConfigExportItem))]
[JsonSerializable(typeof(ProviderConfigExportItem[]))]
[JsonSerializable(typeof(ProviderRuntimeConfig))]
[JsonSerializable(typeof(TestProviderConnectionRequest))]
[JsonSerializable(typeof(SaveProviderConfigRequest))]
[JsonSerializable(typeof(ReorderProvidersRequest))]
[JsonSerializable(typeof(RequestAnalyticsSnapshot))]
[JsonSerializable(typeof(RequestAnalyticsSummary))]
[JsonSerializable(typeof(ListenerStatus))]
[JsonSerializable(typeof(RequestLogEntry))]
[JsonSerializable(typeof(RequestLogEntry[]))]
[JsonSerializable(typeof(UpdateCheckResult))]
[JsonSerializable(typeof(UpdateSourceCheckResult))]
[JsonSerializable(typeof(UpdateSourceCheckResult[]))]
[JsonSerializable(typeof(UpdateReleaseInfo))]
[JsonSerializable(typeof(UpdateAssetInfo))]
[JsonSerializable(typeof(UpdateDownloadRequest))]
[JsonSerializable(typeof(UpdateDownloadResult))]
[JsonSerializable(typeof(VsCodeUserDirectory))]
[JsonSerializable(typeof(VsCodeUserDirectory[]))]
[JsonSerializable(typeof(VsCodeConfigApplyResult))]
[JsonSerializable(typeof(VsCodeOllamaConfigStatus))]
[JsonSerializable(typeof(VsCodeConfigFileChange))]
[JsonSerializable(typeof(VsCodeConfigFileChange[]))]
[JsonSerializable(typeof(VsCodeConfigFieldChange))]
[JsonSerializable(typeof(VsCodeConfigFieldChange[]))]
[JsonSerializable(typeof(VsCodeConfigBackup))]
[JsonSerializable(typeof(VsCodeConfigBackup[]))]
[JsonSerializable(typeof(VsCodeConfigRestoreResult))]
[JsonSerializable(typeof(ManagedOllamaConfig))]
[JsonSerializable(typeof(ManagedOllamaModel))]
[JsonSerializable(typeof(ManagedOllamaModel[]))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(IReadOnlyList<OllamaChatMessage>))]
[JsonSerializable(typeof(IReadOnlyList<OllamaModelInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ProviderConfigView>))]
[JsonSerializable(typeof(IReadOnlyList<ProviderConfigExportItem>))]
[JsonSerializable(typeof(IReadOnlyList<RequestLogEntry>))]
[JsonSerializable(typeof(IReadOnlyList<UpdateSourceCheckResult>))]
[JsonSerializable(typeof(IReadOnlyList<VsCodeUserDirectory>))]
[JsonSerializable(typeof(IReadOnlyList<VsCodeConfigFileChange>))]
[JsonSerializable(typeof(IReadOnlyList<VsCodeConfigFieldChange>))]
[JsonSerializable(typeof(IReadOnlyList<VsCodeConfigBackup>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(JsonElement))]
internal sealed partial class VSCopilotSwitchJsonContext : JsonSerializerContext;
